In [39]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and result.

import numpy as np
import pandas as pd

from IPython.display import display

# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [40]:
# solution
my_array = np.zeros(10)
my_array[4] = 1  # Remember: Python indexing starts at 0, so index 4 is the fifth element.
print("Task 1.1 - Array of 10 zeros with the fifth element set to 1:")
print(my_array)
print()


Task 1.1 - Array of 10 zeros with the fifth element set to 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]



### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [41]:
import numpy as np

# Create a 4x4 matrix with values ranging from 0 to 15
matrix_4x4 = np.arange(16).reshape(4, 4)

# Display the matrix
print("Task 1.2 - 4x4 matrix with values 0 to 15:")
print(matrix_4x4)
print()

Task 1.2 - 4x4 matrix with values 0 to 15:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [42]:
arr1 = np.array([[41, 30, 10],
                 [ 6, 35, 23],
                 [23, 9, 10]])
arr2 = np.array([[4, 29, 2],
                 [5, 13, 3],
                 [24, 16, 7]])

# Element-wise addition, subtraction, multiplication, and division
add_result = arr1 + arr2
sub_result = arr1 - arr2
mul_result = arr1 * arr2
div_result = arr1 / arr2

print("Task 1.3 - Element-wise addition:")
print(add_result)
print("\nTask 1.3 - Element-wise subtraction:")
print(sub_result)
print("\nTask 1.3 - Element-wise multiplication:")
print(mul_result)
print("\nTask 1.3 - Element-wise division:")
print(div_result)
print()

Task 1.3 - Element-wise addition:
[[45 59 12]
 [11 48 26]
 [47 25 17]]

Task 1.3 - Element-wise subtraction:
[[37  1  8]
 [ 1 22 20]
 [-1 -7  3]]

Task 1.3 - Element-wise multiplication:
[[164 870  20]
 [ 30 455  69]
 [552 144  70]]

Task 1.3 - Element-wise division:
[[10.25        1.03448276  5.        ]
 [ 1.2         2.69230769  7.66666667]
 [ 0.95833333  0.5625      1.42857143]]



### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [43]:

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])


sliced_arr = arr[2:7]  

print("Task 1.4 - Sliced array (elements from index 2 to 6):")
print(sliced_arr)
print()


Task 1.4 - Sliced array (elements from index 2 to 6):
[30 40 50 60 70]



### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [44]:
# NB: round the mean to two decimal places
data_array = np.array([[15, 18, 20],
                       [15, 30, 8],
                       [25, 30, 60]])
mean_val = round(data_array.mean(), 2)  # Rounded to two decimal places
sum_val = data_array.sum()
max_val = data_array.max()

print("Task 1.5 - Data array:")
print(data_array)
print("\nMean (rounded to 2 decimal places):", mean_val)
print("Sum:", sum_val)
print("Max:", max_val)
print()

Task 1.5 - Data array:
[[15 18 20]
 [15 30  8]
 [25 30 60]]

Mean (rounded to 2 decimal places): 24.56
Sum: 221
Max: 60



# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [45]:
series_data = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
print("Task 2.1 - Pandas Series:")
print(series_data)
print()

Task 2.1 - Pandas Series:
a    10
b    20
c    30
d    40
e    50
dtype: int64



### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [46]:
import pandas as pd
df = pd.read_csv("data/data.csv")
df

Name  Age  Salary
0     Alice   29   73193
1       Bob   53   85398
2   Charlie   36   47162
3     David   22   65853
4       Eve   24   36168
5     Frank   58   69657
6     Grace   41   85202
7    Hannah   38   62421
8     Isaac   50   74641
9      Jack   47   38963
10    Karen   34   32136
11      Leo   49   41874
12     Mona   56   34070
13     Nina   49   91734
14    Oscar   30   89539
15     Paul   23   78720
16    Quinn   31   54424
17   Rachel   54   59900
18    Steve   36   32163
19     Tina   56   52054

### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [47]:
df_first_three = df.head(3)
print("Task 2.3 - First three rows of the DataFrame:")
print(df_first_three)
print()


Task 2.3 - First three rows of the DataFrame:
      Name  Age  Salary
0    Alice   29   73193
1      Bob   53   85398
2  Charlie   36   47162



### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [61]:

df["Tax"] = df["Salary"] * 0.10 

#### Filter the dataframe by the column "age" whereby the age is above 36 yearsd

In [49]:
# Filter the dataframe where age is above 36
filtered_df = df[df['Age'] > 36]


print(filtered_df)

      Name  Age  Salary
1      Bob   53   85398
5    Frank   58   69657
6    Grace   41   85202
7   Hannah   38   62421
8    Isaac   50   74641
9     Jack   47   38963
11     Leo   49   41874
12    Mona   56   34070
13    Nina   49   91734
17  Rachel   54   59900
19    Tina   56   52054


# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [50]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()

Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [51]:
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})

# Total sales per region
total_sales = sales_data.groupby("Region")["Sales"].sum().reset_index(name="TotalSales")
# Mean sales per region
mean_sales = sales_data.groupby("Region")["Sales"].mean().reset_index(name="MeanSales")

print("Task 3.1 - Total Sales per Region:")
print(total_sales)
print("\nTask 3.1 - Mean Sales per Region:")
print(mean_sales)
print()

Task 3.1 - Total Sales per Region:
  Region  TotalSales
0  North        2200
1  South        2800
2   West        3500

Task 3.1 - Mean Sales per Region:
  Region  MeanSales
0  North     1100.0
1  South     1400.0
2   West     1750.0



### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [52]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print("Customers:")
print(customers.head(2))
print("\nOrders:")
print(orders.head(2))

CustomerID CustomerName
0           1        Alice
1           2          Bob

OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400

In [53]:
# solution
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

merged_data = pd.merge(customers, orders, on="CustomerID", how="inner")
print("Task 3.2 - Merged Customers and Orders Data:")
print(merged_data)
print()

Task 3.2 - Merged Customers and Orders Data:
   CustomerID CustomerName  OrderID  Amount
0           1        Alice      101     250
1           2          Bob      102     400
2           2          Bob      103     600
3           4        David      104     150



### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [58]:
# NB: No test for this. Just an exercise for you to play around with
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})


print("Employess:")
print(employees.head(2))
print("\nDepartments:")
print(departments.head(2))

Employess:
   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2

Departments:
   DeptID DeptName
0       1       HR
1       2  Finance


In [55]:
# solution
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

left_join = pd.merge(employees, departments, on="DeptID", how="left")
print("Task 3.3 - Left Join of Employees and Departments:")
print(left_join)
print()

Task 3.3 - Left Join of Employees and Departments:
   EmpID EmpName  DeptID DeptName
0    101    John       1       HR
1    102    Jane       2  Finance
2    103   Alice       2  Finance
3    104     Bob       3      NaN



### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [56]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [57]:
# solution
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

pivot_table = pd.pivot_table(sales_pivot_data, 
                             values="Sales", 
                             index="Region", 
                             columns="Product", 
                             aggfunc="sum", 
                             fill_value=0)
print("Task 3.4 - Pivot Table (Total Sales for each Region and Product):")
print(pivot_table)

Task 3.4 - Pivot Table (Total Sales for each Region and Product):
Product    A    B
Region           
North    200  300
South    150  400
West     250  500
